services:
  mariadb:
    image: lscr.io/linuxserver/mariadb
    container_name: mariadb
    environment:
      - PUID=1000
      - PGID=1000
      - TH=Asia/Bangkok
      - MYSQL_USER=root
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
    volumes:
      - data:/config
    ports:
      - 3306:3306
    restart: unless-stopped

volumes:
  data:

networks:
  default:
    external: true
    name: base
